# Generated by Django 3.1.2 on 2021-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(help_text='Логин пользователя, добавившего фотографию', max_length=20)),
                ('upload_datetime', models.DateTimeField(auto_now=True, help_text='Время добавления фотографии')),
                ('image', models.ImageField(upload_to='C:\\Users\\Артур\\Desktop\\epremyan\\epremyan\\media')),
            ],
        ),
    ]
